### ISSUE TITLE
Not able to open account dropdown, cart and product page, getting error of vue.js in console.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1208]
- Framework Version: 0.1.6

-------------------------------------------------
Getting this issue from latest master branch

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

-----------------------------------------

Fixed

**Comment by M-Abdullahi** [comment]
Hi. I am also facing this problem.

**Comment by rahulshukla-webkul** [comment]
Hi @M-Abdullahi 

Kindly take pull from our git repository. ( https://github.com/bagisto/bagisto ) 

Thanks

**Comment by M-Abdullahi** [comment]
Hi. I tried pulling from the master branch but i'm still facing the problem.

**Comment by rahulshukla-webkul** [comment]
Hi @M-Abdullahi 

Kindly clear your browser cache and if still error is there then run - 'npm run watch' at 'Shop', 'Admin' & 'UI' package.

**Comment by M-Abdullahi** [comment]
I managed to fix it as instructed. Thanks :+1:
