### ISSUE TITLE
Error when you create or update a new catalog under root

### ISSUE THREAD

**Issue by gfd6th** [bagisto/bagisto#2752]
The same error on demo site
https://demo.bagisto.com/bagisto-200147018122d2/admin/catalog/categories/edit/176

Like title says. When you update this category or create a new category
![image](https://user-images.githubusercontent.com/6814715/77406160-2eeb3800-6def-11ea-96ee-505d9b0bf941.png)

```
Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` between 15 and 16 then `_lft`-1 when `_lft` between 14 and 16 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` between 15 and 16 then `_rgt`-1 when `_rgt` between 14 and 16 then `_rgt`+2 else `_rgt` end where (`_lft` between 14 and 16 or `_rgt` between 14 and 16))
```

I have check the categories table schema
```
CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `position` int(11) NOT NULL DEFAULT '0',
  `image` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `_lft` int(10) unsigned NOT NULL DEFAULT '0',
  `_rgt` int(10) unsigned NOT NULL DEFAULT '0',
  `parent_id` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `display_mode` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT 'products_and_description',
  `category_icon_path` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `categories__lft__rgt_parent_id_index` (`_lft`,`_rgt`,`parent_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
```

and my app/database.php
```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => env('DB_PREFIX'),
            'strict' => false,
            'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
        ],
```

**Comment by gfd6th** [comment]
Fixed the issue. Change the collation in database.

**Comment by senbai** [comment]
@gfd6th  i still have the issue, can you help me with that?

**Comment by digiapps** [comment]
> Fixed the issue. Change the collation in database.

How you fixed that?

**Comment by gfd6th** [comment]
@senbai @digiapps 
https://github.com/bagisto/bagisto/blob/e2cdfbac7f7c602b2ca317d6e67e898a2fd5aa44/config/database.php#L51
Change config in database, make sure it is same with your database

**Comment by bappi2097** [comment]
I have also same issue. And i already change 'collation' How can i fixed this?

**Comment by fio4** [comment]
General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` >= 14 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` >= 14 then `_rgt`+2 else `_rgt` end where (`_lft` >= 14 or `_rgt` >= 14))

'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => env('DB_PREFIX'),
            'strict' => false,
            'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',

**Comment by ErmelindaRapoli** [comment]
I have solved that error in this way:

1) check the collation defined in your database.php of your Laravel project (in my case the collation was 'collation' => 'utf8mb4_unicode_ci'
2) For my project I'm using PhpMyAdmin to inspect my database contents, so login into PhpMyAdmin
3) I change the collation of database and set into utf8mb4_unicode_ci **with the two options enabled to change all collations in the tables and all collations of table fields**, as you can see in this screenshot
![Capture](https://user-images.githubusercontent.com/12624882/83035648-01fb1180-a03a-11ea-9861-c04b1f188a9c.PNG)

**Comment by rajnibalayadavtest** [comment]
I am unable change the collation of database and set into utf8mb4_unicode_ci with the two options enabled to change all collations in the tables and all collations of table fields,from phpmyadmin 
Could you please suggest any other solution as I am facing the same problem.

**Comment by mashekwa** [comment]
Dis anyone successfully solve this?
I still get the error despite  database.php and my database being using 'collation' => 'utf8mb4_unicode_ci',

**Comment by Deepanjali-Singh** [comment]
> I have solved that error in this way:
> 
> 1. check the collation defined in your database.php of your Laravel project (in my case the collation was 'collation' => 'utf8mb4_unicode_ci'
> 2. For my project I'm using PhpMyAdmin to inspect my database contents, so login into PhpMyAdmin
> 3. I change the collation of database and set into utf8mb4_unicode_ci **with the two options enabled to change all collations in the tables and all collations of table fields**, as you can see in this screenshot
>    ![Capture](https://user-images.githubusercontent.com/12624882/83035648-01fb1180-a03a-11ea-9861-c04b1f188a9c.PNG)

I changed the character encoding to match the collation in my database.php but still get the error

**Comment by piersky** [comment]
I confirm that doing as suggested by @ErmelindaRapoli I fixed. The issue was that the tables were right but the database no, it had utf8mb4_general_ci.

Thanks.
