### ISSUE TITLE
save address return error 500

### ISSUE THREAD

**Issue by lYesterdaYl** [bagisto/bagisto#3025]
# Bug report

### Title
Unable to go to next step on checkout. stuck at save address.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. live demo version

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. login with customer account
    2. add product to cart
    3. choose address then nothing happen. It shows error in inspect

![image](https://user-images.githubusercontent.com/5135163/81375821-2a38c580-90b7-11ea-8b56-19825045f531.png)

### Expected result
**Tell us what should happen.**

should go to payment section.

### Actual result

stuck in choose address section.

**Comment by rahulcs0082** [comment]
Hello @lYesterdaYl 

We have fixed this issue on the master, kindly take a pull from it.

**Comment by lYesterdaYl** [comment]
> Hello @lYesterdaYl
> 
> We have fixed this issue on the master, kindly take a pull from it.

Hi, do you mind to tell me which commit is that? thanks.

**Comment by vaishaliwebkul** [comment]
@lYesterdaYl 
update the code with commit https://github.com/bagisto/bagisto/commit/b42ccbfa9e719c8526b249bbfef1951a894d0705

Thanks.

**Comment by vaishaliwebkul** [comment]
@lYesterdaYl 
Hope your query is resolved. Feel free to reopen the issue if still exist.

Thanks

**Comment by yosirn** [comment]
I've just installed a fresh copy  but still facing the same issue.
---
Request URL:https://my.domain/checkout/save-address
Request Method:POST
Remote Address:68.000.01.01:443
Status Code:
500
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
-----
![Screenshot from 2020-05-17 17-31-40](https://user-images.githubusercontent.com/10193377/82155448-927c6980-9864-11ea-8116-f6fedadd1c28.png)

**Comment by vaishaliwebkul** [comment]
@yosirn 
Please update the code from the master branch then 

run 
**composer dump-autoload
  php artisan config:cache
  php artisan vendor:publish**
