### ISSUE TITLE
"error!options are missing alert" on home page shouldn't be shown

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3231]
# Bug report

### Title
"error!options are missing alert" on home page shouldn't be shown

### Issue Description
"error!options are missing alert" on home page shouldn't be shown

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- create a booking, configurable product
    2. step2- click on add to cart button from the home page, (showing error alert before redirect to the product page, it creating confusion for the visitors)

### Expected result
 

- As expected, the error alert shouldn't show on home page, it should be reflected after customer redirected to the product page

- also, the alert is warning message, so kindly show a warning in "YELLOW" color instead of "RED"

### Actual result

![Screenshot](https://user-images.githubusercontent.com/43210406/84481761-2dc1fc80-acb4-11ea-82c4-107e71ff5839.png)

**Comment by vaishaliwebkul** [comment]
fixed

**Comment by stoney024** [comment]
When will it be released?

**Comment by stoney024** [comment]
I've tested the new https://github.com/bagisto/bagisto/releases/tag/v1.2.0-BETA1 release, where it's stated that bug 3231 is fixed and released.

#3231 "error!options are missing alert" on home page shouldn't be shown

Unfortunatelly the bug still exists, except now it's Warning! not an Error! 

![Demo_store](https://user-images.githubusercontent.com/1021260/90749340-9e4c5180-e2d3-11ea-97bd-aba9023d8d2c.png)

**Comment by bhanu-webkul** [comment]
@stoney024 
Agree with you. Thanks for notifying us
