### ISSUE TITLE
Can't locate path for migrations in bagisto/packages

### ISSUE THREAD

**Issue by howdu** [bagisto/bagisto#3807]
Clean install via zip file and composer install but when publishing assets shows error: Can't locate path

```
Copied Directory [/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views] To [/resources/views/errors]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied File [/vendor/flynsarmy/db-blade-compiler/config/.gitkeep] To [/storage/app/db-blade-compiler/views/.gitkeep]
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Attribute/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/BookingProduct/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Category/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Checkout/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Core/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Customer/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Inventory/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Product/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Sales/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Tax/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/User/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/CatalogRule/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/CartRule/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/CMS/src/resources/database/migrations>
Can't locate path: </Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/Velocity/src/resources/database/migrations>
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/Admin/publishable/assets] To [/public/vendor/webkul/admin/assets]
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/Ui/publishable/assets] To [/public/vendor/webkul/ui/assets]
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/Shop/publishable/assets] To [/public/themes/default/assets]
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/Velocity/publishable/assets] To [/public/themes/velocity/assets]
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/Velocity/src/Resources/views/shop] To [/resources/themes/velocity/views]
Copied Directory [/vendor/bagisto/bagisto/packages/Webkul/BookingProduct/publishable/assets] To [/public/themes/default/assets]
Copied Directory [/packages/Webkul/UpgradeVersion/publishable/assets] To [/public/vendor/webkul/upgrade-version/assets]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Mail/resources/views] To [/resources/views/vendor/mail]
Publishing complete.
```

Environment is docker nginx 1.6 / php-fpm 7.3.16

Looking at the code inside class CartRuleServiceProvider it loads the migrations from:
$this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');

But composer is looking in resources with lowercase:
/Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/CartRule/src/resources/database/migrations

The real path is:
/Users/john/Sites/bagisto/vendor/bagisto/bagisto/packages/Webkul/CartRule/src/Database/Migrations

**Comment by devansh-webkul** [comment]
Hi @howdu,

May I know the steps to reproduce this bug. For e.g. setting up db, config files and which command you run for publishing.

**Comment by CodeCures** [comment]
has anyone been able to fix this. am having the same issues and lot other errors
This is what happens when i run php artisan vendor:publish
![publish_error](https://user-images.githubusercontent.com/20299519/92336312-1fa73080-f097-11ea-80ae-85303c208f77.JPG)

Well, I thought it was a minor issue until i tried to login to admin dashboard and that's where i gave up

![admin_error](https://user-images.githubusercontent.com/20299519/92336409-166a9380-f098-11ea-95e5-062be2cd57d5.JPG)

**Comment by vaishaliwebkul** [comment]
Steps to reproduce:

 `composer create-project bagisto/bagisto-standard`

Run 
php artisan migrate
php artisan db:seed
php artisan vendor:publish and press 0

**Comment by hakimwd** [comment]
hi, may I know if this issue has been resolved? I still encountered this issue

**Comment by hakimwd** [comment]
I just found the resolution to this issue, for those interested.

the issue is related to this library that resided in laravel project: vendor/konekt/concord/src/Conventions/ConcordDefault.php

`    
public function migrationsFolder(): string
{
        // return 'resources/database/migrations';
        return 'database/migrations';
   
 }
`

inside file ConcordDefault.php, change line 147 like above. I just commented out the library code and replace with new line `return database/migrations;`.

now, run command `php artisan vendor:publish` should work as usual.

**Comment by devansh-webkul** [comment]
> I just found the resolution to this issue, for those interested.
> 
> the issue is related to this library that resided in laravel project: vendor/konekt/concord/src/Conventions/ConcordDefault.php
> 
> `    
> public function migrationsFolder(): string
> {
>         // return 'resources/database/migrations';
>         return 'database/migrations';
>    
>  }
> `
> 
> inside file ConcordDefault.php, change line 147 like above. I just commented out the library code and replace with new line `return database/migrations;`.
> 
> now, run command `php artisan vendor:publish` should work fine.

@hakimwd 

But this is not a right way, you cannot write the line in the vendor folder directly instead you need to overide this.

Otherwise you will face problem in updating dependencies.

Please check this PR i.e. https://github.com/bagisto/bagisto/pull/3920, this issue is already fixed.

**Comment by sergiocntr** [comment]
![image](https://user-images.githubusercontent.com/7195587/95024510-b90c3700-0683-11eb-89dc-6f4816dcd791.png)

**Comment by sergiocntr** [comment]
![image](https://user-images.githubusercontent.com/7195587/95024732-48feb080-0685-11eb-9e26-7d28d8a7d6cc.png)

**Comment by sergiocntr** [comment]
Sorry , I'm new.
github clone,did php artisan bagisto:install command.
1) still get error message about path
2) now I ended up to have 2 folders : one bagisto and one bagisto-standard that look like the same . The second has itself one vendor/bagisto/bagisto   nearly as clone ....seems something strange to me....

**Comment by sergiocntr** [comment]
![image](https://user-images.githubusercontent.com/7195587/95025129-e8bd3e00-0687-11eb-86e9-e0cdf163f423.png)

**Comment by vaishaliwebkul** [comment]
@sergiocntr 
you may follow the below steps to install the bagisto

1. download the zip from here https://bagisto.com/en/download/
2. unzip the respective zip
3. run composer create-project inside project root directory
4. go to the .env and add database credentials

run the below commands
>php artisan migrate
>php artisan db:seed
>php artisan vendor:publish --force

**Comment by sergiocntr** [comment]
thank you @vaishaliwebkul 
now it works on my local machine  but online not...
http://developteamgold.altervista.org/ecommerce/bagisto/public/
es I can't add users, admin page http://developteamgold.altervista.org/ecommerce/bagisto/admin/login not found
Thanks again for your time I'm quite a newbie

**Comment by vaishaliwebkul** [comment]
@sergiocntr 
make sure the rewrite_mode is enabled in the apache configuration.

**Comment by vaishaliwebkul** [comment]
@howdu 
this bug is fixed now. 
kindly install bagisto from the master branch and check.

**Comment by devansh-webkul** [comment]
This issue is now completely resolved. If someone is having an issue then please take a pull from master or check the PR in this issue i.e.,

1. https://github.com/bagisto/bagisto/pull/3920
2. https://github.com/bagisto/bagisto/pull/4230

**Comment by kazmi99** [comment]
How can I resolve this error when I am getting it on c-Panel?
