### ISSUE TITLE
Sometimes photos removing

### ISSUE THREAD

**Issue by plyaskin** [bagisto/bagisto#9800]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

v2.1.2

### Issue Description

Sometimes photos after saving are removed from the Product. It was twice but after I couldn't repeat it to understand the reason why.

### Preconditions

No one product.

### Steps to reproduce

1. Add the photo to the Product and Save. - Everything is fine.
2. Add one more photo to the Product and Save. - The first photo was removed.
3. Add one more photo to the Product and Save. - The first photo was removed again.
4. Add one more photo to the Product and Save. - Everything is fine again.
It was with 2 products in a row but the photos for the third product are OK.

### Expected Result

All added photos are saved.

### Actual Result

Some photos were removed

### Additional context

It is not BAGisto, it is BUGisto yet.

**Comment by ashishkumar-webkul** [comment]
Thank you so much for your contribution to Bagisto. We really appreciate it.

I have checked and verified the issue that was reported from your end.

Upon investigation, I found that the issue related to adding images in V2.1.2 was indeed appearing. Please refer to the video below for clarification.

https://github.com/bagisto/bagisto/assets/92721837/694492ad-0488-4932-8985-25717ba443a6


However, I'm happy to inform you that this issue has been fixed, and there are no such issues appearing in the latest code, which can be accessed from the master branch. You can find the latest code at the following link: [Master branch link](https://github.com/bagisto/bagisto.git).

Please refer to the video for further clarification.


https://github.com/bagisto/bagisto/assets/92721837/2e262e21-a322-4002-9e4c-bb2d724d6e3c

**Comment by plyaskin** [comment]
Thank you for the reply.
But the video doesn't work.

**Comment by plyaskin** [comment]
I have checked the latest code and the issue is still there.

**Comment by jitendra-webkul** [comment]
[screen_record_1716202720750.webm](https://github.com/bagisto/bagisto/assets/39991107/0316bba9-b758-4e86-b7f8-3495df6df433)


Check again, still not able to reproduce the issue

**Comment by plyaskin** [comment]
Nice, maybe it was some failure and after release, it will work for me.
